// Mock data for UMKM forms
// Provides category options, province-city mapping, and sample seed items

export const kategoriData = [
  { id: "makanan-utama", label: "Makanan Utama" },
  { id: "makanan-ringan", label: "Makanan Ringan" },
  { id: "minuman", label: "Minuman" },
  { id: "dessert", label: "Dessert" },
  { id: "bumbu-saus", label: "Bumbu & Saus" },
]

export const provinsiKotaData: Record<string, string[]> = {
  "jawa-barat": ["Bandung", "Bogor", "Sukabumi", "Bekasi"],
  "jawa-tengah": ["Semarang", "Solo", "Yogyakarta", "Pekalongan"],
  "jawa-timur": ["Surabaya", "Malang", "Gresik", "Lamongan"],
  "sumatra-utara": ["Medan", "Deli Serdang", "Pematang Siantar"],
  "sumatra-selatan": ["Palembang", "Lahat", "Musi Rawas"],
  bali: ["Denpasar", "Ubud", "Sanur", "Seminyak"],
  "sulawesi-utara": ["Manado", "Tomohon", "Bitung"],
  "sulawesi-selatan": ["Makassar", "Palopo", "Kendari"],
}

export const seedKulinerItems = [
  {
    id: "1",
    nama: "Rendang Daging",
    kategori: "makanan-utama",
    deskripsi:
      "Rendang daging adalah masakan tradisional Indonesia yang berasal dari Minangkabau, Sumatera Barat. Hidangan ini dibuat dari daging sapi yang dimasak dengan santan dan rempah-rempah pilihan seperti cabe merah, bawang merah, bawang putih, jahe, kunyit, dan serai. Proses memasak rendang memerlukan waktu yang cukup lama hingga daging empuk dan warna berubah menjadi cokelat kehitaman. Tekstur rendang yang kaya dengan rempah membuat cita rasanya yang tak terlupakan.",
    provinsi: "sumatra-utara",
    kota: "Medan",
    hargaMin: 35000,
    hargaMax: 50000,
    bahan: [
      "Daging sapi 1 kg",
      "Santan 500 ml",
      "Cabe merah 8 buah",
      "Bawang merah 6 siung",
      "Bawang putih 3 siung",
      "Jahe 3 cm",
      "Kunyit 2 cm",
      "Serai 2 batang",
      "Garam, gula, dan merica secukupnya",
    ],
    langkah: [
      "Iris semua bumbu halus di blender dengan sedikit air",
      "Panaskan wajan, tumis bumbu halus hingga harum",
      "Masukkan daging sapi, aduk hingga tercampur rata",
      "Tuang santan sedikit demi sedikit sambil terus diaduk",
      "Masak dengan api sedang hingga daging empuk dan kuah menyusut (sekitar 1.5 jam)",
      "Aduk sesekali agar tidak gosong",
      "Rendang siap disajikan",
    ],
    foto: ["/rendang-daging-tradisional-minangkabau.jpg"],
    lat: 3.5952,
    lng: 98.6722,
    status: "published",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    nama: "Gado-Gado",
    kategori: "makanan-utama",
    deskripsi:
      "Gado-gado adalah salah satu hidangan sayuran tradisional Indonesia yang populer, terutama di Jawa. Hidangan ini terdiri dari berbagai sayuran yang direbus atau dikukus seperti kubis, wortel, tauge, dan buncis, yang disajikan dengan saus kacang yang kaya rasa. Kacang yang digunakan adalah kacang tanah yang digiling halus dan dicampur dengan bumbu rempah. Gado-gado biasanya dilengkapi dengan tahu goreng, telur rebus, dan lontong atau nasi kuning.",
    provinsi: "jawa-barat",
    kota: "Bandung",
    hargaMin: 15000,
    hargaMax: 25000,
    bahan: [
      "Kubis 250g",
      "Wortel 1 buah",
      "Tauge 150g",
      "Buncis 150g",
      "Tahu 200g",
      "Telur 2 butir",
      "Kacang tanah 200g",
      "Cabe rawit 5 buah",
      "Bawang putih 2 siung",
      "Garam dan gula secukupnya",
      "Minyak goreng secukupnya",
    ],
    langkah: [
      "Rebus kubis, wortel, tauge, dan buncis hingga matang namun tetap renyah",
      "Goreng tahu hingga kuning keemasan",
      "Rebus telur hingga matang",
      "Blender kacang tanah, cabe rawit, dan bawang putih dengan air secukupnya",
      "Tuang dalam wajan, tambahkan air secukupnya, garam dan gula",
      "Masak saus kacang hingga mendidih dan mengental",
      "Susun sayuran di piring, letakkan tahu dan telur di atasnya",
      "Tuangkan saus kacang dan sajikan",
    ],
    foto: ["/gado-gado-indonesia-makanan-sayuran.jpg"],
    lat: -6.9175,
    lng: 107.6019,
    status: "published",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "3",
    nama: "Teh Tarik",
    kategori: "minuman",
    deskripsi:
      'Teh tarik adalah minuman tradisional yang terkenal di Malaysia dan juga populer di Indonesia. Minuman ini dibuat dari teh yang diseduh dengan air panas dan dikombinasikan dengan susu kental manis. Nama "tarik" berasal dari teknik menyajiannya yang unik, yaitu menuangkan minuman dari gelas satu ke gelas lain dari ketinggian tertentu untuk mendapatkan busa dan tekstur yang sempurna. Teknik ini membuat minuman lebih sejuk dan menciptakan lapisan busa yang lezat.',
    provinsi: "bali",
    kota: "Denpasar",
    hargaMin: 8000,
    hargaMax: 12000,
    bahan: [
      "Teh hitam 1 kantong",
      "Susu kental manis 2 sdm",
      "Air panas 200 ml",
      "Gula secukupnya",
      "Es batu (untuk versi dingin)",
    ],
    langkah: [
      "Seduh teh hitam dengan air panas dalam gelas atau teko",
      "Biarkan teh terendam selama 2-3 menit hingga warnanya cokelat",
      "Tuang teh ke gelas lain beberapa kali sambil menahan tinggi untuk membentuk busa",
      "Tambahkan susu kental manis dan gula sesuai selera",
      "Tarik kembali teh dari ketinggian beberapa kali untuk mendapatkan tekstur sempurna",
      "Sajikan dengan atau tanpa es batu",
    ],
    foto: ["/teh-tarik-minuman-tradisional.jpg"],
    lat: -8.6705,
    lng: 115.2126,
    status: "published",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
]